repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: Run pytest with coverage
        entry: bash -c 'pytest tests/ --cov=. --cov-report=term-missing --cov-fail-under=80 -q'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
